# Application root-application

application_metadata_name:  "service-application"
application_metadata_namespace: "service-application"
application_destination_namespace: "service-application"
application_destination_name: "in-cluster"
application_project: "service-application"
application_source_repo_url: "https://github.com/nighoa/gitops-app-of-apps"
application_source_path: "service-applications"

# Project root-application

project_metadata_name:  "service-application"
project_metadata_namespace: "service-application"
project_destination_namespace: "*"
project_destination_name: "in-cluster"
project_destination_server: "https://kubernetes.default.svc"
project_source_repo_url: "https://github.com/nighoa/gitops-app-of-apps"

# Repository root-application

repository_metadata_name:  "github.com-nighoa-gitops-app-of-apps"
repository_metadata_namespace: "service-application"
repository_stringData_url: "https://github.com/nighoa/gitops-app-of-apps"
