apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: grafana
    server: {{ .Values.spec.destination.server }}
  project: cluster-svc
  source:
    path: apps/grafana
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: HEAD
    helm:
      releaseName: grafana
      valueFiles:
        - ../../apps/grafana/values.yml