apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: drupal-testing
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: drupal-testing
    server: {{ .Values.spec.destination.server }}
  project: applications
  source:
    path: apps/drupal
    repoURL: {{ .Values.applications.drupal.source.repoURL }}
    targetRevision: {{ .Values.applications.drupal.source.targetRevision }}
    helm:
      releaseName: helm-drupal-ademe
      valueFiles:
        - ../../apps/drupal/values.yaml
    syncPolicy:
      syncOptions:
      - CreateNamespace=true