apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: drupal-testing
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: drupal-testing
    server: {{ .Values.applications.drupalservice.destination.server }}
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
  project: applications
  source:
    path: apps/drupal
    repoURL: {{ .Values.applications.drupalservice.source.repoURL }}
    targetRevision: {{ .Values.applications.drupalservice.source.targetRevision }}
    helm:
      releaseName: helm-drupal-ademe
      valueFiles:
        - ../../apps/drupal/values-{{ .Values.applications.drupalservice.source.env }}.yaml