apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: drupal
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: drupal
    server: {{ .Values.spec.destination.server }}
  project: applications
  source:
    path: apps/drupal
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: HEAD
    helm:
      releaseName: drupal
      valueFiles:
        - ../../apps/drupal/values.yml