apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: drupalmulticluster
spec:
  generators:
  - list:
      elements:
      - cluster: service
        url: in-cluster
      - cluster: preprod
        url: kapsule_cluster_horsprod
  template:
    metadata:
      name: 'drupal-testing'
    spec:
      destination:
        namespace: drupal-testing
        name: '{{url}}'
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true
        - PruneLast=true
      project: applications
      source:
        path: apps/drupal
        repoURL: {{ .Values.applications.drupalpreprod.source.repoURL }}
        targetRevision: {{ .Values.applications.drupalpreprod.source.targetRevision }}
        helm:
          releaseName: helm-drupal-ademe
          valueFiles:
            - ../../apps/drupal/values-{{ .Values.applications.drupalpreprod.source.env }}.yaml