apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: drupalmulticluster
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: cluster-service
        env: service
        destination: in-cluster
      - cluster: cluster-preprod
        env: preprod
        destination: kapsule_cluster_horsprod
  template:
    metadata:
      name: 'drupal-testing-{{env}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      destination:
        namespace: drupal-testing
        name: '{{destination}}'
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true
        - PruneLast=true
      project: applications
      source:
        path: apps/drupal
        repoURL: {{ .Values.applications.drupalpreprod.source.repoURL }}
        targetRevision: {{ .Values.applications.drupalpreprod.source.targetRevision }}
        helm:
          releaseName: helm-drupal-ademe
          valueFiles:
            - ../../apps/drupal/values-{{ .Values.applications.drupalpreprod.source.env }}.yaml