apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: monitoring
  source:
    chart: grafana
    helm:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.50.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true