spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/nighoa/gitops-app-of-apps.git
    targetRevision: HEAD

applications:
  drupal:
    source:
      repoURL: https://github.com/nighoa/gitops-app-of-apps.git
      targetRevision: HEAD