apiVersion: v1
kind: Secret
metadata:
  name: {{ default "template" .Values.front.drupal.recaptchaSecretKeySecretName | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.front.drupal.recaptchaSecretKeyValue }}
  secret_key: {{ default "" .Values.front.drupal.recaptchaSecretKeyValue | b64enc | quote }}
  {{- else }}
  secret_key: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.front.drupal.recaptchaSiteKeyValue }}
  site_key: {{ default "" .Values.front.drupal.recaptchaSiteKeyValue | b64enc | quote }}
  {{- else }}
  site_key: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}

