---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-crt-{{ .Values.grafana.fqdn }}
  namespace: grafana
spec:
  secretName: grafana-tls
  dnsNames:
    - {{ .Values.grafana.fqdn }}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod